### ISSUE TITLE
anycatch-v4-prefixes.csv not updated since a week

### ISSUE THREAD

**Issue by laurentpellegrino** [bgptools/anycast-prefixes#2]

**Comment by benjojo** [comment]
Yeah the v4 anycast is provided by a 3rd party, and it appears that the
self checks (aka, testing if 1.1.1.1 and 8.8.8.8 are considered anycast)
are failing, I'm going to ask the operator who runs it what might be wrong,
at worse I will hunt around for a new provider

**Comment by laurentpellegrino** [comment]
Thanks for your answer. It looks like it is failing again but this time for both IPv4 and IPv6.

**Comment by benjojo** [comment]
I've manually kicked it again and it should be back
